apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: java-spring
        image: tiim32/iti0302-2024:latest
        ports:
        - containerPort: 8080