apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    {{- range $key, $value := .Values.database.labels }}
      {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.database.labels }}
        {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.database.labels }}
          {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.database.container.name }}
        image: {{ .Values.database.image.repository}}:{{ .Values.database.image.tag }}
        ports:
        - containerPort: {{ .Values.database.container.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.database.configMap.name }}