---
  - name: Template master.sh script to control-plane node
    ansible.builtin.template:
      src: master.sh.j2
      dest: /root/master.sh
      owner: root
      group: root
      mode: '0700'

  - name: Run master.sh on first start
    ansible.builtin.command:
      cmd: bash /root/master.sh
      creates: /usr/bin/kubeadm
  
  - name: Store file for worker to join
    ansible.builtin.fetch:
      src: /root/join-command.sh
      dest: /tmp/join-command.sh/
      flat: true
  
  #- name: Remove taint from master_node
  #  kubernetes.core.k8s:
  #    state: patched
  #    kind: 
