---
- name: Initial setup
  hosts: all
  remote_user: root
  roles:
    - init
  tags: init

- name: Setup control-plane node
  hosts: control_plane
  remote_user: root
  roles:
    - control-node
  tags: control