apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.configMap.name }}
  namespace: {{ .Values.application.namespace }}
data:
  {{- range $key, $value := .Values.database.env }}
    {{ $key }}: {{ $value }}
  {{- end }}