apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.application.namespace }}
  name: {{ .Values.database.service.name }}
spec:
  selector:
    {{- range $key, $value := .Values.database.labels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432