apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: frontend
          image: tiim32/frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "backend-service:8080"