apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  namespace: {{ .Values.application.namespace }}
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-spring
  template:
    metadata:
      labels:
        app: java-spring
    spec:
      containers:
        - name: java-spring
          image: tiim32/iti0302-2024:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: java-spring-config
