apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    app: java-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080