apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.application.namespace }}
  name: database-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432