apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.application.namespace }}
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007