---
  - name: Template worker.sh script to worker node
    ansible.builtin.template:
      src: worker.sh.j2
      dest: /root/worker.sh
      owner: root
      group: root
      mode: '0700'

  - name: Run worker.sh on first start
    ansible.builtin.command:
      cmd: bash /root/worker.sh
      creates: /usr/bin/kubeadm


  - name: Change kubelet default IP
    ansible.builtin.lineinfile:
      path: /etc/default/kubelet
      regexp: '^KUBELET_EXTRA_ARGS='
      line: "KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['private_networks'] | map(attribute='ip') | select('match', '^192\\.168\\.0\\.\\d+$') | list | first }}"
      create: yes

  - name: Restart kubelet
    ansible.builtin.systemd:
      name: kubelet
      state: restarted
      enabled: yes

  - name: Copy worker join command to host
    ansible.builtin.copy:
      src: /tmp/join-command.sh
      dest: /root/join-command.sh
  
  - name: Run join-command.sh to join cluster
    ansible.builtin.command:
      cmd: bash /root/join-command.sh
      creates: /etc/kubernetes/pki/ca.crt
