apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configMap.name }}
  namespace: {{ .Values.application.namespace }}
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://{{ .Values.database.service.name }}:5432/{{ .Values.database.env.POSTGRES_DB }}
    spring.datasource.username={{ .Values.database.env.POSTGRES_USER }}
    spring.datasource.password={{ .Values.database.env.POSTGRES_PASSWORD }}
    spring.datasource.driver-class-name=org.postgresql.Driver
    LOCAL_JWT_SECRET_KEY=localSecretKeyValue
    logging.level.org.springframework.security=DEBUG
    spring.datasource.initialization-mode=always
    spring.sql.init.continue-on-error=true
    spring.sql.init.mode=always