apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configMap.name }}
  namespace: {{ .Values.application.namespace }}
data:
  application.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://database-service:5432/devdb
        username: devuser
        password: devpassword
        driver-class-name: org.postgresql.Driver
      liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml
    LOCAL_JWT_SECRET_KEY: localSecretKeyValue
    logging:
      level:
        org:
          springframework:
            security: DEBUG
