application:
  name: urbex
  namespace: urbex

backend:
  name: backend
  container:
    name: java-spring
    port: 8080
  image:
    repository: tiim32/iti0302-2024
    tag: latest
  replicas: 2
  labels:
    app: backend
  service:
    name: backend-service
    type: NodePort
    port: 80
    nodePort: 30008
  configMap:
    name: java-spring-config

frontend:
  name: frontend
  container:
    name: react
    port: 5173
  image:
    repository: tiim32/frontend
    tag: latest
  replicas: 2
  env:
    VITE_API_URL: "http://backend-service:30008"
  labels:
    app: frontend
  service:
    name: frontend-service
    type: NodePort
    port: 80
    nodePort: 30007

database:
  container:
    name: postgres
    port: 5432
  image:
    repository: postgres
    tag: latest
  name: database
  replicas: 1
  env:
    POSTGRES_DB: devdb
    POSTGRES_USER: devuser
    POSTGRES_PASSWORD: devpassword
    PGDATA: /var/lib/postgresql/data/pgdata
  labels:
    app: postgres
  port: 5432
  service:
    name: postgres-service
    type: ClusterIP
    port: 5432
  configMap:
    name: postgres-config