---
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: web-app
      api_version: v1
      kind: Namespace
      state: present

  - name: Get project root directory
    set_fact:
      project_root: "{{ lookup('pipe', 'pwd') }}"

  - name: Copy k8s manifests to control-plane node
    ansible.builtin.copy:
      src: "{{ project_root }}/k8s/"
      dest: "/root/k8s"
      mode: '0700'
  
  - name: Template values.yaml to control-plane node
    ansible.builtin.template:
      src: values.yaml.j2
      dest: /root/values.yaml
      owner: root
      group: root
      mode: '0700'

  - name: Apply Urbex helm chart on the control-plane node
    kubernetes.core.helm:
      name: urbex
      chart_ref: "/root/k8s/helm/urbex"
      release_namespace: urbex
      create_namespace: true
      values_files:
      - /root/values.yaml