---
  - name: Update APT cache
    ansible.builtin.apt:
      cache_valid_time: 86400
  
  - name: Create custom /etc/hosts file
    ansible.builtin.template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'