---
  - name: Update APT cache
    ansible.builtin.apt:
      cache_valid_time: 86400
  
  - name: Install preequisites for Docker
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
      state: present
  
  - name: Add Docker GPG signing key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Add Docker apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
      state: present
      filename: docker
  
  - name: Update APT cache
    ansible.builtin.apt:
      update_cache: true
  
  - name: Install preequisites for Kubernetes and Docker
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - gpg
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
  
  - name: Enable containerd and docker
    ansible.builtin.service:
      name:
        - containerd
        - docker
      state: enabled

  - name: Containerd configuration
    ansible.builtin.file:
      src: config.toml
      dest: /etc/containerd/config.toml
    notify:
      - Restart Containerd
      - Restart Docker
  
  - name: Add an Kubernetes Apt signing key, uses whichever key is at the URL
    ansible.builtin.apt_key:
      url: "{{ kubernetes_signing_key }}"
      state: present

  - name: Run command to add Kubernetes apt repo
    ansible.builtin.command:
      cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] "{{ kubernetes_signing_key }}" /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
      creates: /etc/apt/sources.list.d/kubernetes.list

  - name: Update APT cache
    ansible.builtin.apt:
      update_cache: true

  - name: Install kubeadm
    ansible.builtin.apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present
  
  - name: Enable kubelet
    ansible.builtin.service:
      name:
        - containerd
        - docker
      state: enabled