apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # Use resources instead of bases

namespace: web-app
configMapGenerator:
  - name: java-spring-config
    files:
      - application.properties
    options:
      disableNameSuffixHash: true

  - name: postgres-config
    literals:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - PGDATA=/var/lib/postgresql/data/pgdata